Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    # for x windows if e.g. using chrome
    #v.gui = true

  end

  # web server for ionic
  config.vm.network "forwarded_port", guest: 8100, host: 8100


  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git curl wget
    
    # try node 10 for now
    curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    sudo apt-get install -y nodejs
    sudo apt-get install -y gcc g++ make
    #sudo apt-get install -y build-essential
    
    # on to standard install instructions from https://github.com/dynamic-music/semantic-player
    sudo npm install -g cordova ionic
    git clone https://github.com/semantic-player/semantic-player.git
    cd semantic-player
    npm install
    #ionic serve --address=0.0.0.0
  SHELL

end
